-- MySQL Script generated by MySQL Workbench
-- 10/18/22 17:01:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema itslibro1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema itslibro1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `itslibro1` DEFAULT CHARACTER SET utf8 ;
USE `itslibro1` ;

-- -----------------------------------------------------
-- Table `itslibro1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itslibro1`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `avatar` BLOB NULL,
  `about_user` VARCHAR(256) NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC),
  UNIQUE INDEX `nick_UNIQUE` (`nick` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itslibro1`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itslibro1`.`books` (
  `id_book` INT NOT NULL AUTO_INCREMENT,
  `id_publisher` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `original_name` VARCHAR(100) NULL,
  `author` VARCHAR(45) NOT NULL,
  `picture` BLOB NULL,
  `data_writed` VARCHAR(50) NOT NULL,
  `data_published` DATE NULL,
  `genres` VARCHAR(256) NOT NULL,
  `page_count` INT NOT NULL,
  `tags` VARCHAR(256) NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `views_count` INT NULL,
  `in_list_count` INT NULL,
  `rating` INT NULL,
  PRIMARY KEY (`id_book`),
  INDEX `publisher_idx` (`id_publisher` ASC),
  CONSTRAINT `publisher`
    FOREIGN KEY (`id_publisher`)
    REFERENCES `itslibro1`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itslibro1`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itslibro1`.`comments` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `id_commenter` INT NOT NULL,
  `id_book` INT NOT NULL,
  `data_comment` DATETIME NOT NULL,
  `comment` VARCHAR(256) NOT NULL,
  `likes` INT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `books_idx` (`id_book` ASC),
  INDEX `user_idx` (`id_commenter` ASC),
  CONSTRAINT `book_com`
    FOREIGN KEY (`id_book`)
    REFERENCES `itslibro1`.`books` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_com`
    FOREIGN KEY (`id_commenter`)
    REFERENCES `itslibro1`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itslibro1`.`publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itslibro1`.`publications` (
  `id_book` INT NOT NULL,
  INDEX `books_idx` (`id_book` ASC),
  CONSTRAINT `books`
    FOREIGN KEY (`id_book`)
    REFERENCES `itslibro1`.`books` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itslibro1`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itslibro1`.`ratings` (
  `id_book` INT NOT NULL,
  `id_user` INT NOT NULL,
  `rating` INT NOT NULL,
  `id_rating` INT NOT NULL,
  INDEX `book_idx` (`id_book` ASC),
  INDEX `user_idx` (`id_user` ASC),
  PRIMARY KEY (`id_rating`),
  CONSTRAINT `book_rate`
    FOREIGN KEY (`id_book`)
    REFERENCES `itslibro1`.`books` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_rate`
    FOREIGN KEY (`id_user`)
    REFERENCES `itslibro1`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itslibro1`.`list_favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itslibro1`.`list_favorite` (
  `id_book` INT NOT NULL,
  `id_user` INT NOT NULL,
  INDEX `user_idx` (`id_book` ASC),
  INDEX `user_idx1` (`id_user` ASC),
  CONSTRAINT `book_fav`
    FOREIGN KEY (`id_book`)
    REFERENCES `itslibro1`.`books` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_fav`
    FOREIGN KEY (`id_user`)
    REFERENCES `itslibro1`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itslibro1`.`list_reading`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itslibro1`.`list_reading` (
  `id_user` INT NOT NULL,
  `id_book` INT NOT NULL,
  INDEX `user_idx` (`id_user` ASC),
  INDEX `book_idx` (`id_book` ASC),
  CONSTRAINT `user_read`
    FOREIGN KEY (`id_user`)
    REFERENCES `itslibro1`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book_read`
    FOREIGN KEY (`id_book`)
    REFERENCES `itslibro1`.`books` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itslibro1`.`list_in_plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itslibro1`.`list_in_plans` (
  `id_user` INT NOT NULL,
  `id_book` INT NOT NULL,
  INDEX `user_idx` (`id_user` ASC),
  INDEX `book_idx` (`id_book` ASC),
  CONSTRAINT `user_plan`
    FOREIGN KEY (`id_user`)
    REFERENCES `itslibro1`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book_plan`
    FOREIGN KEY (`id_book`)
    REFERENCES `itslibro1`.`books` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itslibro1`.`list_readed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itslibro1`.`list_readed` (
  `id_user` INT NOT NULL,
  `id_book` INT NOT NULL,
  INDEX `user_idx` (`id_user` ASC),
  INDEX `book_idx` (`id_book` ASC),
  CONSTRAINT `user_readed`
    FOREIGN KEY (`id_user`)
    REFERENCES `itslibro1`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book_readed`
    FOREIGN KEY (`id_book`)
    REFERENCES `itslibro1`.`books` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itslibro1`.`list_abandoned`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itslibro1`.`list_abandoned` (
  `id_user` INT NOT NULL,
  `id_book` INT NOT NULL,
  INDEX `user_idx` (`id_user` ASC),
  INDEX `book_idx` (`id_book` ASC),
  CONSTRAINT `user_abandoned`
    FOREIGN KEY (`id_user`)
    REFERENCES `itslibro1`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book_abandoned`
    FOREIGN KEY (`id_book`)
    REFERENCES `itslibro1`.`books` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
